name: Release
on:
  push:

    branches: [master]
  pull_request:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo RELOADAGENT | gpg-connect-agent
        shell: bash           
      - name: Set Git to sign commits
        run: |
          git config --global user.name "B3D CI/CD"
          git config --global user.email "mo@b3d.com.pl"
          git config --global commit.gpgsign true
          git config --global user.signingkey 1BBE0FE0B65C2C04
          git config --global gpg.program gpg        

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Create minimal package.json and install pull-request plugin
        run: |
          echo '{}' > package.json
          npm install --save-dev semantic-release-github-pullrequest          

      - name: Release to GitHub
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git
          branches: |
            ['master']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: semantic-release:*,semantic-release-github-pullrequest*
